name: Python Image AI Training

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
        cache: pip
        cache-dependency-path: ./.cache/pip  # تحديد المسار المناسب هنا

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Train AI model
      run: python simple_ai_model.py

    - name: Save trained model
      run: mv trained_model.h5 App/models/trained_model.h5  # تحديد مسار حفظ النموذج المدرب
      if: success()

    - name: Generate image from description
      run: python generate_image.py
